Change rubocop to development dependency.
prontolabs/pronto-haml pull request #11
Opened 2021-05-03 15:23 UTC by nashby

It's not required here.

2021-05-04 04:43 UTC, ashkulz requested changes
From what I can see, it's a [dependency of haml-lint](https://github.com/sds/haml-lint/blob/master/haml_lint.gemspec) and it was explicitly added as there were test failures with post-1.0 versions -- see 99c406b90de6bbb3d460ec0fff3a1219f9c4b7a6.

If you look at the CI for this PR, it still installs rubocop `0.93.1` -- if you remove this line, the checks will fail. If you can spend some time in investigating the failing tests that'd be great.

2021-05-04 06:14 UTC, nashby commented
@ashkulz hey! Thanks for reviewing it! I tried to remove explicit version declaration for rubocop and tests pass for me locally. Can you please approve running workflow here to see if it fails?

2021-05-04 06:25 UTC, ashkulz commented
Hmm, you're right -- I added it because the [earlier attempt failed](https://github.com/prontolabs/pronto-haml/actions?query=branch%3Anew_release) -- it's quite possible it was only an issue with some specific RuboCop versions, but can't verify as the logs are gone. Considering that rubocop isn't a direct dependency, I don't think testing a bunch of versions in a matrix makes sense, like was done in prontolabs/pronto-rubocop@a59ab3594c3bf0e55fb28b02e12fd610a6f3539d -- what do you think?

2021-05-04 06:33 UTC, nashby commented
@ashkulz yeah, for me doesn't really make sense to test rubocop here. Also now I noticed that this repo has .rubocop.yml file so I guess we have to add it to dev dependency anyway?

2021-05-04 06:45 UTC, ashkulz approved these changes
It gets pulled in via `haml-lint` anyway, so I guess it's fine for now.

2021-05-04 06:46 UTC, merged

2021-05-13 11:32 UTC, gingerlime commented
bumped into this as well see https://github.com/rubocop/rubocop-rails/issues/14#issuecomment-840493689

Can you guys publish a new Gem version with this fix?

2021-06-21 04:31 UTC, ashkulz commented
@gingerlime sure, I'll do that sometime this week.

2021-07-08 03:26 UTC, PikachuEXE commented
Still waiting for this fix...

2021-11-15 05:16 UTC, ashkulz commented
Pushed to RubyGems, sorry for the delay!